[build]
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "https://miro-estore.netlify.app/*"
  to = "https://miro-estore-app.herokuapp.com/:splat"
  status = 301
  force = true